### ISSUE TITLE
Can't find '__main__' module in './'

### ISSUE THREAD

**Issue by ramifications123** [chris-lovejoy/YouTube-video-finder#5]
Followed directions and won't run.

**Comment by chris-lovejoy** [comment]
Try running 'python3 main.py' explicitly, rather than 'python3 ./'

**Comment by chris-lovejoy** [comment]
At some point __main__.py was accidentally switched to main.py, so this prevented the above command from finding the right file - I'll amend the instructions

**Comment by ramifications123** [comment]
Good to go, it worked perfectly. Thanks
