### ISSUE TITLE
Any idea

### ISSUE THREAD

**Issue by m-reyes-h** [chris-lovejoy/YouTube-video-finder#9]
python main.py 'search term 1' 'search term 2'
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value

**Comment by chris-lovejoy** [comment]
Looks like it's a numpy-related issue: https://github.com/twintproject/twint/issues/1030

Are you using numpy1.19.4 on Windows? Try installing 1.19.3 if so, as per thread above

Issue closed - please re-open if error continues
